### PR TITLE
Test

### PR DESCRIPTION
**Pull request by SpacePossum**
Hi!

During testing and reviewing your PR I noticed there was code unused in the utest.
After removing a bit the tests stayed green.
Could you review my review-PR?

### CODE REVIEW

**Comment by owebia** [comment]
Did you check the modifications by running php-cs-fixer diff on php-cs-fixer source code?

**Comment by SpacePossum** [comment]
no I didn't, only on modified code, are there case that are not covered by utest?

**Comment by owebia** [comment]
I think, yes

**Comment by SpacePossum** [comment]
Alright, thanks! I'll leave this for now and think about how to proceed.

**Pull request closed without merging**
